# fix pbpaste and pbcopy on tmux
set-option -g default-command "reattach-to-user-namespace -l zsh"

# nice colors FTW
set -g default-terminal "screen-256color"

# set left portion of status bar to maximum of 40 chars
set-option -g status-left-length 40

# use C-b p to copy tmux buffer to OS clipboard
bind C-p run-shell "reattach-to-user-namespace -l zsh -c 'tmux show-buffer | pbcopy'"

# vim bindings for copy mode
setw -g mode-keys vi
bind [ copy-mode
bind -t vi-copy v begin-selection
bind -t vi-copy y copy-selection
bind -t vi-copy V rectangle-toggle
bind ] paste-buffer

# C-p space to paste text from one of the buffers
bind Space choose-buffer

# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# switch to a session that start with the given name
bind S command-prompt -p session: "run-shell 'tmux-switch-session \"%%\"'"
