set nocompatible                " choose no compatibility with legacy vi
syntax enable
set encoding=utf-8
set showcmd                     " display incomplete commands

filetype off                   " required!
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'
Bundle "vim-ruby/vim-ruby"
Bundle 'tpope/vim-rails'
Bundle 'wincent/Command-T'
Bundle 'sjbach/lusty'
Bundle 'tpope/vim-fugitive'

filetype plugin indent on       " load file type plugins + indentation

set hidden " For lusty explorer

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode
set list                        " Show invisible characters

" List chars
set listchars=""                  " Reset the listchars
set listchars=tab:\ \             " a tab should display as "  ", trailing whitespace as "."
set listchars+=trail:.            " show trailing spaces as dots
set listchars+=extends:>          " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen
set listchars+=precedes:<         " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

" cancel highlight with space
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

set number
set ruler

" Disable bell
set vb

" over 80 columns highlighting
set textwidth=80
set colorcolumn=+1 " highlight column after 'textwidth' 
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey 

let mapleader = ","

" Command-T config
let g:CommandTMaxFiles=20000
nnoremap <leader>t :CommandT<CR>
nnoremap <leader>b :LustyBufferExplorer<CR>
nnoremap <leader>lb :LustyBufferGrep<CR>

colorscheme molokai

" Toggle paste mode
nmap <silent> <F4> :set invpaste<CR>:set paste?<CR>
imap <silent> <F4> <ESC>:set invpaste<CR>:set paste?<CR>

" Next buffer
nmap <silent> ,. :bnext<CR>

" Previous buffer
nmap <silent> ,m :bprev<CR>

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Easy split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Make Y behave like other capitals
map Y y$

" automatically reload vimrc when it's saved
au BufWritePost .vimrc so ~/.vimrc
