set nocompatible                " choose no compatibility with legacy vi
set encoding=utf-8
set showcmd                     " display incomplete commands

filetype off                   " required for Vundle

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'terryma/vim-multiple-cursors'
Plugin 'gmarik/vundle'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'sjbach/lusty'
Plugin 'tpope/vim-fugitive'
Plugin 'kchmck/vim-coffee-script'
Plugin 'scrooloose/nerdcommenter'
Plugin 'nono/vim-handlebars'
Plugin 'kien/ctrlp.vim'
Plugin 'exu/pgsql.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tpope/vim-surround'
Plugin 'mileszs/ack.vim'
Plugin 'godlygeek/tabular'
Plugin 'tpope/vim-bundler'
Plugin 'myusuf3/numbers.vim'
Plugin 'vim-scripts/AutoTag'
Plugin 'JazzCore/ctrlp-cmatcher'

call vundle#end()

filetype plugin indent on       " load file type plugins + indentation

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

set showmode                    " show current mode
set number                      " enable line numbers
set visualbell                  " no bell sound
set autoread                    " reload files changed outside of vim

set hidden                      " allow hidden buffers 

let mapleader=","

" turn off swap files, I never used it anyway
set noswapfile
set nobackup
set nowb

if has('persistent_undo')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" List chars
set listchars=""                  " Reset the listchars
set listchars=tab:\ \             " a tab should display as "  ", trailing whitespace as "."
set listchars+=trail:.            " show trailing spaces as dots
set listchars+=extends:>          " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen
set listchars+=precedes:<         " The character to show in the last column when wrap is
                                  " off and the line continues beyond the right of the screen

set nowrap              " don't wrap lines

set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

set wildmode=list:longest
set wildmenu

set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" map jk as ESC
inoremap jk <Left><C-[>]

" cancel highlight with space
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" don't add files that are usually not needed in ctrlp for better speed
let g:ctrlp_user_command = 'find %s -type f \( ! -path "node_modules/*" ! -path "*/vendor/bundle*" ! -path "*.git/*" ! -path "*/.*" ! -path "*/tmp/*" ! -path "tmp/*" ! -name "*.so" ! -name "*.swp" ! -name "*.zip" ! -name "*.png" ! -name "*.jpg" ! -path "*/b/*" \)'
" use cmatcher, it's much faster than the default
let g:ctrlp_match_func = {'match' : 'matcher#cmatch' }

" Play nice with tmux
set term=screen-256color

set ruler " show line and column number on the bottom

set textwidth=80 " set text width to 80 chars
set colorcolumn=+1 " visually show the text width
set fo-=tc " but don't wrap automatically (will still allow to rewrap with gq)
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey

" shortcuts for LustyBufferExplorer
nnoremap <leader>b :LustyBufferExplorer<CR>
nnoremap <leader>lb :LustyBufferGrep<CR>
nnoremap <leader>h :LustyFilesystemExplorerFromHere<CR>

" Solarized Colorscheme Config
let g:solarized_contrast="high"    "default value is normal
let g:solarized_visibility="high"    "default value is normal
let g:solarized_diffmode="high"    "default value is normal
syntax enable
set background=light
colorscheme solarized

" Toggle paste mode (no automatic indentation)
nmap <silent> <F4> :set invpaste<CR>:set paste?<CR>
imap <silent> <F4> <ESC>:set invpaste<CR>:set paste?<CR>

" Next buffer
nmap <silent> ,. :bnext<CR>

" Previous buffer
nmap <silent> ,m :bprev<CR>

" Easy split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" syntax highlighting for sql files
au BufNewFile,BufRead *.sql setf pgsql

" Use unnamed register by default
set clipboard=unnamed
